language: go

go:
  - 1.11.x
  - master

matrix:
  allow_failures:
    - go: master

sudo: false

env:
  - GO111MODULE=on

install:
  - go mod download

script:
  - make ci-test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
